language: python
sudo: false
cache: false
python:
    - '2.7'
    - '3.5'
    - '3.6'
install:
  - pip install -U tox coveralls

script:
  - coverage erase
  - tox
after_success:
  - coverage combine
  - coveralls

notifications:
  email:
    - a.vara.1986@gmail.com
